# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not. (Left hand side & right hand side)

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[4,5],[7,8]])
A.shape

(3, 2)

In [3]:
B = np.array([[3,2],[1,2]])
B.shape

(2, 2)

In [4]:
C = np.array([[8,9],[3,6]])
C.shape

(2, 2)

In [5]:
left = np.dot(A,B+C)
left

array([[ 19,  27],
       [ 64,  84],
       [109, 141]])

In [6]:
right = np.dot(A,B) + np.dot(A,C)
right

array([[ 19,  27],
       [ 64,  84],
       [109, 141]])

In [7]:
left == right

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [11]:
A

array([[1, 2],
       [4, 5],
       [7, 8]])

In [12]:
B

array([[3, 2],
       [1, 2]])

In [13]:
C

array([[8, 9],
       [3, 6]])

In [8]:
lhs = np.dot(A,B@C)
lhs

array([[ 58,  81],
       [190, 261],
       [322, 441]])

In [9]:
rhs = np.dot(A,B)@C
rhs

array([[ 58,  81],
       [190, 261],
       [322, 441]])

In [10]:
lhs == rhs

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [71]:
lh = np.dot(B,C)
lh

array([[30, 39],
       [14, 21]])

In [72]:
rh = np.dot(C,B)
rh

array([[33, 34],
       [15, 18]])

In [73]:
lh == rh

array([[False, False],
       [False, False]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [74]:
E = np.array([[2, 3], [1, 4], [7, 6]])
F = np.array([[5, 3], [2, 2]])

left = np.transpose(E.dot(F))
right = np.transpose(F).dot(np.transpose(A))
left == right

array([[False, False, False],
       [False, False, False]])

In [75]:
A.shape

(3, 2)

In [89]:
A

array([[1, 2],
       [4, 5],
       [7, 8]])

In [77]:
A

array([[1, 2],
       [4, 5],
       [7, 8]])

In [78]:
A.shape

(3, 2)

In [79]:
A_Trans = np.transpose(A)
A_Trans

array([[1, 4, 7],
       [2, 5, 8]])

In [80]:
A_Trans.shape

(2, 3)

In [91]:
Y = np.array([[1,2],[2,1],[1,2]])
Y

array([[1, 2],
       [2, 1],
       [1, 2]])

In [92]:
Y.shape

(3, 2)

In [93]:
lhs = np.dot(A_Trans,Y)
lhs

array([[16, 20],
       [20, 25]])

In [94]:
rhs = np.dot(np.transpose(Y),A)
rhs

array([[16, 20],
       [20, 25]])

In [95]:
lhs == rhs

array([[ True,  True],
       [ True,  True]])

#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [86]:
lhs = np.transpose(np.dot(A,B))
lhs

array([[ 5, 17, 29],
       [ 6, 18, 30]])

In [87]:
rhs = np.transpose(B).dot(np.transpose(A))
rhs

array([[ 5, 17, 29],
       [ 6, 18, 30]])

In [88]:
lhs == rhs

array([[ True,  True,  True],
       [ True,  True,  True]])

## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 